name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cancel_previous:

    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # 0.9.1
        with:
          workflow_id: ${{ github.event.workflow.id }}

  core-test:
    needs: cancel_previous
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: cache gradle dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-core-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-core-
    - name: Run Tests
      run: ./gradlew core:test
    - name: Generate coverage report
      run: ./gradlew core:codeCoverageReport
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@50ffd5fc58ed613b7848c7604df3a1effc13d659 # v2.1.0

  android-test:
    needs: cancel_previous
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-android-
      - name: Run Tests
        run: ./gradlew android:test
      - name: Generate coverage report
        run: ./gradlew android:codeCoverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@50ffd5fc58ed613b7848c7604df3a1effc13d659 # v2.1.0

  destination-test:
    needs: cancel_previous
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-dest-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-dest-
      - name: Run Tests
        run: ./gradlew samples:kotlin-android-app-destinations:test
      - name: Generate coverage report
        run: ./gradlew samples:kotlin-android-app-destinations:codeCoverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@50ffd5fc58ed613b7848c7604df3a1effc13d659 # v2.1.0

  security:
    needs: cancel_previous
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Snyk
        run: ./gradlew snyk-test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
